#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.image_proxy != "" and data.values.image_proxy_username != "":

#@overlay/match by=overlay.subset({"kind": "StatefulSet", "metadata": {"name": "pgsql-postgresql"}})
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      imagePullSecrets:
        - name: registry-credentials

#@ end
