#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

#@ if data.values.image_proxy != "" and data.values.image_proxy_username != "":

#@ def dockerconfigjson():
#@   auth = base64.encode(data.values.image_proxy_username + ":" + data.values.image_proxy_password)
#@   return json.encode({"auths": {data.values.image_proxy: {"username": data.values.image_proxy_username, "password": data.values.image_proxy_password, "auth": auth}}})
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: postgres
  labels:
    app: doc
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ base64.encode(dockerconfigjson())

#@ end
